### ISSUE TITLE
error while running sudo hackingtool

### ISSUE THREAD

**Issue by vishwa6184** [Z4nzu/hackingtool#242]
┌──(root㉿kali)-[~/hackingtool]
└─# sudo hackingtool
Traceback (most recent call last):
  File "/usr/share/doc/hackingtool/hackingtool.py", line 11, in <module>
    from tools.ddos import DDOSTools
  File "/usr/share/doc/hackingtool/tools/ddos.py", line 29
    "sudo", "python3 ddos", method, url, socks_type5.4.1, threads, proxylist, multiple, timer])
                                         ^^^^^^^^^^^^^
SyntaxError: invalid syntax. Perhaps you forgot a comma?

this is the error i get while running sudo hacking tool

**Comment by vinh9x** [comment]
Me too. 
![image](https://user-images.githubusercontent.com/101310543/167363148-80008f0b-da2a-41d7-8bfd-16cfe7cdd340.png)

**Comment by vinh9x** [comment]
I have tried many times. but still can't

**Comment by SnipeZoidYT** [comment]
same idk how to fix it so if you do please help

**Comment by Samer666569** [comment]
Me too

**Comment by hmody3000** [comment]
i will fix it

`socks_types5.4.1 must be "socks_types5.4.1"` in file ddos.py if you want edit it with `sudo nano` or `sudo mousepad` in line 29

**Comment by pextris** [comment]
> i will fix it
> 
> `socks_types5.4.1 must be "socks_types5.4.1"` in file ddos.py edit it with `sudo nano` or `sudo mousepad` in line 29

This worked for me.

**Comment by hmody3000** [comment]
@pextris im happy that worked for you

**Comment by shagene** [comment]
could someone post their ddos file to compare to? I feel like updating mine didnt change anything.

Thanks.

**Comment by Aikanaro1973** [comment]
Guarda qui https://github.com/Z4nzu/hackingtool/issues/241#issue-1228067456

**Comment by cclauss** [comment]
Fixed in #176
