### ISSUE TITLE
SyntaxError: invalid syntax

### ISSUE THREAD

**Issue by ANIWAIFUS** [Z4nzu/hackingtool#252]
i came across this thing:
Traceback (most recent call last):
  File "/usr/share/doc/hackingtool/hackingtool.py", line 11, in <module>
    from tools.ddos import DDOSTools
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/share/doc/hackingtool/tools/ddos.py", line 29
    "sudo", "python3 ddos", method, url, socks_type5.4.1, threads, proxylist, multiple, timer])
                                         ^^^^^^^^^^^^^
SyntaxError: invalid syntax. Perhaps you forgot a comma?

can you help me?

**Comment by cclauss** [comment]
Fixed in #176
