### ISSUE TITLE
**Describe the bug**

### ISSUE THREAD

**Issue by bubon4ik222** [Z4nzu/hackingtool#316]
**Describe the bug**
Use `./hack-browser-data -vv` paste result here
```
[x]:  Get 24439 history, filename is results/firefox_history.csv
[x]:  Get 27 download history, filename is results/firefox_download.csv
panic: runtime error: slice bounds out of range [:-12]

goroutine 1 [running]:
hack-browser-data/core/decrypt.PKCS5UnPadding(...)
        /source/core/decrypt/decrypt.go:189
hack-browser-data/core/decrypt.aes128CBCDecrypt({0xc000648140, 0xc0002e8c54, 0xefb8ca50}, {0xc0002e8c60, 0x10, 0x10}, {0xc0002e8c40, 0x10, 0x10})
        /source/core/decrypt/decrypt.go:182 +0x159
hack-browser-data/core/decrypt.MetaPBE.Decrypt({{{0xc00063e280, 0x7, 0xa}, {{{...}, {...}}, {{...}, {...}}}}, {0xc0002e8c40, 0x10, 0x10}}, ...)
        /source/core/decrypt/decrypt.go:144 +0x195
hack-browser-data/core/data.(*passwords).FirefoxParse(0xc000064a00)
        /source/core/data/parse.go:665 +0x196
hack-browser-data/cmd.Execute.func1(0xc000092000)
        /source/cmd/cmd.go:91 +0x51e
github.com/urfave/cli/v2.(*App).RunContext(0xc00008e000, {0x4cfa10, 0xc0000100d8}, {0xc000020080, 0x5, 0x8})
        /go/pkg/mod/github.com/urfave/cli/v2@v2.2.0/app.go:315 +0x8ac
github.com/urfave/cli/v2.(*App).Run(...)
        /go/pkg/mod/github.com/urfave/cli/v2@v2.2.0/app.go:215
hack-browser-data/cmd.Execute()
        /source/cmd/cmd.go:115 +0x890
main.main()
        /source/main.go:8 +0x17
```

**Desktop (please complete the following information):**
 - OS Name: Windows 11, x86_64
 - Browser Name: Firefox
 - Browser Version: 95.0.2

**Additional context**
Firefox 密码管理器设置了主密码

__Originally posted by @stephanoskomnenos in https://github.com/moonD4rk/HackBrowserData/issues/109__

**Comment by bubon4ik222** [comment]
> **Describe the bug**
> 
> Use `./hack-browser-data -vv` paste result here
> 
> ```
> 
> [x]:  Get 24439 history, filename is results/firefox_history.csv
> 
> [x]:  Get 27 download history, filename is results/firefox_download.csv
> 
> panic: runtime error: slice bounds out of range [:-12]
> 
> 
> 
> goroutine 1 [running]:
> 
> hack-browser-data/core/decrypt.PKCS5UnPadding(...)
> 
>         /source/core/decrypt/decrypt.go:189
> 
> hack-browser-data/core/decrypt.aes128CBCDecrypt({0xc000648140, 0xc0002e8c54, 0xefb8ca50}, {0xc0002e8c60, 0x10, 0x10}, {0xc0002e8c40, 0x10, 0x10})
> 
>         /source/core/decrypt/decrypt.go:182 +0x159
> 
> hack-browser-data/core/decrypt.MetaPBE.Decrypt({{{0xc00063e280, 0x7, 0xa}, {{{...}, {...}}, {{...}, {...}}}}, {0xc0002e8c40, 0x10, 0x10}}, ...)
> 
>         /source/core/decrypt/decrypt.go:144 +0x195
> 
> hack-browser-data/core/data.(*passwords).FirefoxParse(0xc000064a00)
> 
>         /source/core/data/parse.go:665 +0x196
> 
> hack-browser-data/cmd.Execute.func1(0xc000092000)
> 
>         /source/cmd/cmd.go:91 +0x51e
> 
> github.com/urfave/cli/v2.(*App).RunContext(0xc00008e000, {0x4cfa10, 0xc0000100d8}, {0xc000020080, 0x5, 0x8})
> 
>         /go/pkg/mod/github.com/urfave/cli/v2@v2.2.0/app.go:315 +0x8ac
> 
> github.com/urfave/cli/v2.(*App).Run(...)
> 
>         /go/pkg/mod/github.com/urfave/cli/v2@v2.2.0/app.go:215
> 
> hack-browser-data/cmd.Execute()
> 
>         /source/cmd/cmd.go:115 +0x890
> 
> main.main()
> 
>         /source/main.go:8 +0x17
> 
> ```
> 
> 
> 
> **Desktop (please complete the following information):**
> 
>  - OS Name: Windows 11, x86_64
> 
>  - Browser Name: Firefox
> 
>  - Browser Version: 95.0.2
> 
> 
> 
> **Additional context**
> 
> Firefox 密码管理器设置了主密码
> 
> 
> 
> __Originally posted by @stephanoskomnenos in https://github.com/moonD4rk/HackBrowserData/issues/109__
