### ISSUE TITLE
Fix Error install pip hackingtool "WARNING: Retrying (Retry(total=4, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ReadTimeoutError("HTTPSConnectionPool(host='files.pythonhosted.org', port=443): Read timed out. (read timeout=15)")': /packages/93/dd/b464b728b866aaa62785a609e0dd8c72201d62c5f7c53e7c20f4dceb085f/build-1.0.3-py3-none-any.whl.metadata"
please help me 🫠

### ISSUE THREAD

**Issue by Honeyrm8595** [Z4nzu/hackingtool#448]

**Comment by m-attz** [comment]
This error is raised due to the short amount of time given for a response from the server. 

Try running: pip install --default-timeout=100 hackingtool

**Comment by Satachuko** [comment]
i guy when i dot "sudo hackingtool" its say this i cant do anything. Can someone help or explain why he do that ?

Traceback (most recent call last):
  File "/usr/share/hackingtool/hackingtool.py", line 105, in <module>
    os.makedirs(archive, exist_ok=True)
  File "<frozen os>", line 225, in makedirs
FileNotFoundError: [Errno 2] No such file or directory: ''

**Comment by m-attz** [comment]
> i guy when i do "sudo hackingtool" its say this i cant do anything. Can someone help or explain why he do that ?
> 
> Traceback (most recent call last): File "/usr/share/hackingtool/hackingtool.py", line 105, in os.makedirs(archive, exist_ok=True) File "", line 225, in makedirs FileNotFoundError: [Errno 2] No such file or directory: '

Navigate to the location of hackingtool.py then run it using Python
