### ISSUE TITLE
Traceback (most recent call last):   File "/usr/share/hackingtool/hackingtool.py", line 105, in <module>     os.makedirs(archive, exist_ok=True)   File "<frozen os>", line 225, in makedirs PermissionError: [Errno 13] Permission denied: '/home/hackingtool/'

### ISSUE THREAD

**Issue by magicdwf** [Z4nzu/hackingtool#457]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by magicdwf** [comment]
if anyone knows how to help me on this i would appreciate it

**Comment by agentdog** [comment]
What operating system are you using? could you provide more information?

Most likely (if on Linux or MacOS) you just need to use `sudo` otherwise (if on Windows) you just need to run the terminal as administrator
