### ISSUE TITLE
Help "<frozen os>", line 225, in makedirs FileNotFoundError: [Errno 2] No such file or director

### ISSUE THREAD

**Issue by Rexadev** [Z4nzu/hackingtool#467]
```
└─$ hackingtool                    
Traceback (most recent call last):
  File "/usr/share/hackingtool/hackingtool.py", line 105, in <module>
    os.makedirs(archive, exist_ok=True)
  File "<frozen os>", line 225, in makedirs
FileNotFoundError: [Errno 2] No such file or directory: ''
```

**Comment by ahma339** [comment]
solution plzz

**Comment by BlackGasper1** [comment]
> os.makedirs(archive

**Comment by SandERFills** [comment]
The problem still exists
Is there any solution?

**Comment by SandERFills** [comment]
I found the file ~/hackingtoolpath.txt and changed the path to the one I set, but nothing.
But from the directory where I installed the files, I launched it through 'python hackertool.py'
